import io
import re

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)

from llm.prompt import load_notes_prompt


def generate_notes_content(router, retriever):
    """
    Use the RAG pipeline to extract structured notes from all documents.
    Makes multiple targeted queries to gather comprehensive content.
    """
    queries = [
        "What are all the main topics, themes, and subjects covered in these documents?",
        "What are the most important concepts, definitions, and key terms explained?",
        "What are the critical data points, statistics, formulas, and findings?",
        "Provide a comprehensive summary of the most important information.",
    ]

    # Gather context from multiple query angles
    all_context = []
    for q in queries:
        context_docs = retriever.invoke(q)
        for doc in context_docs:
            content = doc.page_content.strip()
            if content and content not in all_context:
                all_context.append(content)

    combined_context = "\n\n".join(all_context)

    # Generate structured notes via LLM
    notes_prompt = load_notes_prompt()
    result = router.complete(
        "notes_generation",
        [{
            "role": "user",
            "content": notes_prompt.format(content=combined_context),
        }],
    )

    return {
        "raw_text": result,
        "context_chunks": len(all_context),
        "model_label": router.get_model_label("notes_generation"),
    }


def _parse_sections(raw_text):
    """Parse the LLM output into sections based on ## headers."""
    sections = []
    current_title = "Overview"
    current_lines = []

    for line in raw_text.split("\n"):
        line = line.strip()
        if line.startswith("## "):
            if current_lines:
                sections.append((current_title, "\n".join(current_lines)))
                current_lines = []
            current_title = line.replace("## ", "").strip()
        elif line:
            current_lines.append(line)

    if current_lines:
        sections.append((current_title, "\n".join(current_lines)))

    return sections


def build_notes_pdf(notes_data):
    """
    Build a beautifully styled Notes PDF using ReportLab.
    Returns the PDF as a BytesIO stream.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        topMargin=50, bottomMargin=50,
        leftMargin=60, rightMargin=60
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "NotesTitle", parent=styles["Title"],
        fontSize=28, textColor=colors.HexColor("#1e1b4b"),
        spaceAfter=6, alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )
    subtitle_style = ParagraphStyle(
        "NotesSubtitle", parent=styles["Normal"],
        fontSize=12, textColor=colors.HexColor("#6366f1"),
        alignment=TA_CENTER, spaceAfter=20,
    )
    section_header_style = ParagraphStyle(
        "SectionHeader", parent=styles["Heading2"],
        fontSize=16, textColor=colors.HexColor("#312e81"),
        spaceBefore=18, spaceAfter=10,
        fontName="Helvetica-Bold",
        borderWidth=0, borderPadding=0,
    )
    body_style = ParagraphStyle(
        "NotesBody", parent=styles["Normal"],
        fontSize=10.5, textColor=colors.HexColor("#1f2937"),
        leading=16, spaceAfter=4,
    )
    bullet_style = ParagraphStyle(
        "NotesBullet", parent=body_style,
        leftIndent=20, bulletIndent=8,
        spaceAfter=3,
    )

    elements = []

    # ── Cover Page ──
    elements.append(Spacer(1, 60))

    elements.append(Paragraph("📝 Study Notes", title_style))
    elements.append(Paragraph("AI-Generated from Your Documents", subtitle_style))
    elements.append(Spacer(1, 10))

    # Decorative line
    elements.append(HRFlowable(
        width="60%", thickness=2,
        color=colors.HexColor("#6366f1"),
        spaceBefore=5, spaceAfter=5,
        hAlign="CENTER",
    ))
    elements.append(Spacer(1, 10))

    info_data = [
        ["Generated by", "MindFolio"],
        ["Source Chunks", str(notes_data.get("context_chunks", "N/A"))],
        ["Model", notes_data.get("model_label", "N/A")],
    ]
    info_table = Table(info_data, colWidths=[120, 200])
    info_table.setStyle(TableStyle([
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#6b7280")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1f2937")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(info_table)
    elements.append(PageBreak())

    # ── Content Pages ──
    sections = _parse_sections(notes_data["raw_text"])

    for section_title, section_body in sections:
        # Section header with colored bar
        header_data = [[Paragraph(section_title, section_header_style)]]
        header_table = Table(header_data, colWidths=[doc.width])
        header_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#eef2ff")),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("ROUNDEDCORNERS", [6, 6, 6, 6]),
        ]))
        elements.append(header_table)
        elements.append(Spacer(1, 6))

        # Section body
        for line in section_body.split("\n"):
            line = line.strip()
            if not line:
                continue
            # Clean markdown bold markers
            line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            if line.startswith("- "):
                content = line[2:].strip()
                elements.append(Paragraph(f"• {content}", bullet_style))
            else:
                elements.append(Paragraph(line, body_style))

        elements.append(Spacer(1, 10))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
